# Generated by Django 2.2 on 2019-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_fifth_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towns', models.CharField(choices=[('kyiv', 'Киев'), ('chernigov', 'Чернигов'), ('odessa', 'Одесса'), ('lvov', 'Львов')], help_text='Выберите городa со списка', max_length=200, verbose_name='Город')),
            ],
        ),
        migrations.RemoveField(
            model_name='author1',
            name='city',
        ),
        migrations.AddField(
            model_name='author1',
            name='city',
            field=models.ManyToManyField(to='lesson_fifth_forms.Cities'),
        ),
    ]
